sudo: required
services:
  - docker
before_install:
  - docker build -t johnwalker721/react-test -f ./client/Dockerfile.dev
script:
  - docker run -e CLI=true USERNAME/react-test npm test -- --coverage
after_success:
  - docker build -t johnwalker721/multi-client ./client
  - docker build -t johnwalker721/multi-worker ./worker
  - docker build -t johnwalker721/multi-server ./server
  - docker build -t johnwalker721/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  - docker push johnwalker721/multi-client 
  - docker push johnwalker721/multi-worker
  - docker push johnwalker721/multi-server
  - docker push johnwalker721/multi-nginx